name: RDS Deployment Workflow to ec2

on:
  push:
    branches:
      - main
    paths:
      - 'backend_rds/**'
  
  workflow_dispatch: # кнопка в самому гітхаб можливість руками запускати
 
defaults:  #для того що б ми змінили робочу дерикторію 
  run:
     working-directory: ./backend_rds
 
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials  # налаштовується CLI для взамодії з AWS servis
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: role--is

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image # Команда збирає Docker-образ розібратись як можна скоротити IMAGE_TAG=${{ github.sha }}   
        run: | 
          IMAGE_TAG=${{ github.sha }}   
          docker build -t backend-rds .  
          docker tag backend-rds:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/backend-rds:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/backend-rds:$IMAGE_TAG


      - name: Connect to EC2 
        run: |
         echo "${{ secrets.SSH_KEY }}" > key.pemAdd commentMore actions
            chmod 600 key.pem
        
            ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} "
              cd /home/ubuntu/f1-store
              echo IMAGE_TAG: ${{ github.sha }}
        
              aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com
        
              # ОНОВЛЕННЯ образу
              docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/backend-rds:${{ github.sha }}
        
              # sed - на правильному файлі і з дефісом
              sed -i '/backend-rds:/,/image:/s|image: .*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/backend-rds:${{ github.sha }}|g' docker-compose.yaml
        
              # Зупинка та видалення всіх контейнерів, які могли зависнути
              docker-compose -f docker-compose.yaml down || true
        
              # Явно видалити "завислі" контейнери (якщо такі лишились)
              docker ps -a --filter 'name=f1-store_' --format '{{.ID}}' | xargs -r docker rm -f
        
              # Тепер можна піднімати проект
              docker-compose -f docker-compose.yaml up -d
        
              echo ${{ github.sha }} >> test.txt 
              uptime
            "
        
            rm key.pem
        