name: RDS Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'backend_rds/**'
  
  workflow_dispatch: # кнопка в самому гітхаб можливість руками запускати
 
defaults:  #для того що б ми змінили робочу дерикторію 
  run:
     working-directory: ./backend_rds
 
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials  # налаштовується CLI для взамодії з AWS servis
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: role--is

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image # Команда збирає Docker-образ розібратись як можна скоротити IMAGE_TAG=${{ github.sha }}   
        run: | 
          IMAGE_TAG=${{ github.sha }}   
          docker build -t backend-rds .  
          docker tag backend-rds:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/backend-rds:$IMAGE_TAG
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com/backend-rds:$IMAGE_TAG


      - name: Connect to EC2 
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_HOST }} << EOF
            cd /home/ubuntu/f1-store
            aws ecr get-login-password --region eu-north-1 \
            | docker login --username AWS --password-stdin 149591431224.dkr.ecr.eu-north-1.amazonaws.com
            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_rds:$IMAGE_TAG
            sed -i '/backend_rds:/,/image:/s|image: .*|image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/backend_rds:$IMAGE_TAG|g' docker-compose.yml
            docker compose down 
            docker compose up -d
            echo "$IMAGE_TAG" >> test.txt 
            uptime
          EOF
          rm key.pem
        